### ISSUE TITLE
New students list

### ISSUE THREAD

**Issue by mikolevy** [autyzm-pg/friendly-plans-react#105]
AC: There is a simple list of all students (just names), ordered alphabetically. We can open this list by clicking a button in the dashboard.

**Comment by mikolevy** [comment]
![image (2)](https://user-images.githubusercontent.com/9366818/64475143-f8194180-d17e-11e9-85e1-6c4fe731753d.png)

**Comment by mikolevy** [comment]
Don't follow the exact modal style - could be done as existing template screen

**Comment by bklukaczewski** [comment]
Modal template is already there - `NarrowScreenTemplate` feel free to use it, but make sure, that the screen is in `RootStackNavigator` as only this one is supporting transparent card screens.

**Comment by dmydlo** [comment]
Changes with logic without styles and some additional code to ease development are available on `105-new-student-list-logic` branch.
