### ISSUE TITLE
Add new Student

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#148]
Add the possibility to add a new student.
It should look like Student Settings, but with: 
- empty Student name (placeholder: "Wpisz imie")
- Header (Ustawienia podopiecznego) changed to "Dodaj podpiecznego"
- default settings as in #74 
- centred button at the bottom
![image](https://user-images.githubusercontent.com/9513577/67674246-488d6e00-f97c-11e9-9a3e-41434f9b94da.png)

![image](https://user-images.githubusercontent.com/9513577/67662964-bcbc1780-f964-11e9-98ca-cb84256ff2a3.png)

**Comment by Raphjagiello** [comment]
Zgadzam się z propozycją Przemka
