### ISSUE TITLE
Popup timer styling

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#151]
**REDESIGN NEEDED**

![image](https://user-images.githubusercontent.com/9513577/66290769-6832f880-e8e0-11e9-900e-be4be8e59cbb.png)

AC:
 - We should display a simple timer, only minutes, 1-60

https://xd.adobe.com/spec/01d5ebeb-d8a4-4a08-7f23-309931817948-77e4/screen/53eb01ec-26c0-4d0e-ac24-e47eec8ac491/WIP-Zadanie-Pojedyncze-timer-modal

**Comment by Raphjagiello** [comment]
Będziemy wyświetlać najprawdopodobniej godziny, minuty i sekundy. Może to jeszcze ulec zmianie i wyrzucimy ewentualnie godziny - czekamy na odpowiedź.
