### ISSUE TITLE
Set the font size depending on settings

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#159]
It is possible to change the font size in Student Settings.
S = 12px
M = 14px
L = 16px
XL = 20px

![image](https://user-images.githubusercontent.com/9513577/66127452-fca11080-e5eb-11e9-96d5-f721dc1bec94.png)

AC:
Changing the font size in settings results in:
- dynamically updated font size in preview in settings
- updated font size in Student View

**Comment by Raphjagiello** [comment]
![Ustawienia podopiecznego – 1](https://user-images.githubusercontent.com/56950541/67634014-3ac1e500-f8b7-11e9-83ec-1831d450693f.png)

Wielkość fontu nie zmienia się przy sliderze. W preview wykorzystujemy wartości obecne już w Style Guide czyli:
S = 12px
M = 14px
L = 16px
XL = 20px

Aby było prościej załączam wam obrazek podglądowy.

**Comment by PrzemekPopowicz** [comment]
To wiemy, tylko jak te ustawienia wpływają na rozmiar tego co widzi podopieczny? 
Wydaje się, że teksty powinny być większe na 'Student View'
