### ISSUE TITLE
Delete a Student

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#161]
Add a button to delete the Student.
![image](https://user-images.githubusercontent.com/9513577/66132689-bbadf980-e5f5-11e9-8841-6ddc29140969.png)

Similar to:
![image](https://user-images.githubusercontent.com/9513577/67674312-71156800-f97c-11e9-9eb5-8f9947d616e7.png)

At the bottom of the student settings bar.

- after delete navigate to the student list / welcome screen

**Comment by Raphjagiello** [comment]
Lepsze wyjście w student settings bar na samym końcu.
