### ISSUE TITLE
Fix search

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#174]
![image](https://user-images.githubusercontent.com/9513577/67198708-cf33cf80-f3ff-11e9-8c62-bd14439ffe07.png)
W designie nie widać za bardzo, że ten X dotyczy czyszczenia i korzystając z apki myli sie, ze Xem mozna cofnąć. 

Rozwiazanie: Schować X jak input searcha jest pusty -> X widoczny tylko jeśli coś jest wpisane (wtedy nawet jak ktoś kliknie X to zauwazy, ze zostanie tylko 'strzalka cofnij' i bedzie wiedzial jak z tego wyjsc).

- X button should clear search
- X button is invisible when there is nothing in the search input
- The students list is sorted alphabetically 
- highlight a matching part of a found text

https://xd.adobe.com/spec/01d5ebeb-d8a4-4a08-7f23-309931817948-77e4/screen/9271d45b-7969-45c7-b93e-fad8b0a29bf8/Lista-podopiecznych-wyszukiwanie-wyniki

**Comment by Raphjagiello** [comment]
Zgadza się!
