### ISSUE TITLE
Task fields validation

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#185]
You should fill all the fields, but it is possible to go back, without filling any of them.

When user is trying to go back without at least one of the field -> display popup:

> "Not all required fields are filled. Do you want to leave anyway?"

> "Nie wszystkie wymagane pola są wypełnione. Czy na pewno chcesz wyjść?"

Yes -> go back to list of tasks
No -> allow the user to finish editing.

**Comment by Raphjagiello** [comment]
Tak, dodalbym że zadanie bez nazwy powinno otrzymać nazwę generyczną jak np. Zadanie bez nazwy 01, podobnie z planem, np. Plan bez nazwy 01
