### ISSUE TITLE
Timer popup (styling)

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#187]
![WIP Zadanie - Pojedyncze – timer modal – 1](https://user-images.githubusercontent.com/56950541/67634819-d146d400-f8c0-11e9-86ec-5940d507609f.png)

AC:
- connected with logic #86 
- fancy wheel input
- Styling as in the mockup:
https://xd.adobe.com/spec/01d5ebeb-d8a4-4a08-7f23-309931817948-77e4/screen/1f0b3e6e-9770-4b55-a4dc-0ac27adb512f/Zadanie-Pojedyncze-timer-modal-1

Sth like this?
https://github.com/KalonTech/ReactNativeWheelPicker

**Comment by Raphjagiello** [comment]
![WIP Zadanie - Pojedyncze – timer modal – 1](https://user-images.githubusercontent.com/56950541/67634819-d146d400-f8c0-11e9-86ec-5940d507609f.png)

Zmiana timera na roller. Zmiana buttonów, zawsze będą występowały w kombinacji: Contained button + text button. X = zamknięcie okna, czyli cancel.
