### ISSUE TITLE
Update settings design

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#212]
https://xd.adobe.com/spec/01d5ebeb-d8a4-4a08-7f23-309931817948-77e4/screen/2b3c4fb3-421a-4e8c-8404-5b7ce5f46609/Ustawienia-podopiecznego

![image](https://user-images.githubusercontent.com/9513577/67664073-335a1480-f967-11e9-868a-5cee6c61e6df.png)

Ustawienia podopiecznego:
- Przy pierwszym sliderze po lewej jest ikona symbolizująca slide i duży obrazek, po prawej jest ikona symbolizująca widok listy. Mają one pomóc w orientacji użytkownika w którą stronę jakie ustawienia się znajdują. Przy drugim slideerze dodałem po lewej małą ikonkę "T", po prawej wielką ikonę "T". Również pomogą w orientacji użytkownika po której stronie slidera znajdują się jakie ikony.
- W drugim sliderze zmieniłem label z "Rozmiar liter" na "Rozmiar tekstu" tak aby korespondowało to ze sliderem wyżej i labelem "Obrazek z tekstem...". Uzyskujemy w ten sposób różnicowanie względem ustawienia "Wielkie litery".
- Toggle switch stan disabled, teraz wykorzystuje szary kolor ze Style Guide'a z szarym tłem backgroundu pod nim ustawionym na opactiy 20%. Dzięki temu zwiększamy jego zauważalność. 
- Analogicznie do powyższej zmiany również kolor separatorów między częściami karty uległ zmianie. Ich kolor jest teraz szarym kolorem ze Style Guide z opacity 20%.

**Comment by bklukaczewski** [comment]
Done in #225
