### ISSUE TITLE
Edit task - Set the timer - as slider

### ISSUE THREAD

**Issue by bklukaczewski** [autyzm-pg/friendly-plans-react#273]
This is MVP version of #86 but instead of using wheel input, we can use slider from 1 to 60 minutes

AC: 
- Set slider from 1 to 60 minutes in task create/edit view
- Save this info on task save

**Comment by mikolevy** [comment]
Playing around I found that it's currently not 100% working as we have

```
updatePlanItem = async (formData: PlanItemFormData) => {
    const { name, nameForChild } = formData;
    await this.state.planItem.update({
      name,
      nameForChild,
    });
```
called onSubmit. Slider and updating form props is done already we need only to update this method to properly save all plan item data (not only name)
