### ISSUE TITLE
[BUG] Display settings for child - wrong icons [D2]

### ISSUE THREAD

**Issue by DorotaBabinska** [autyzm-pg/friendly-plans-react#45]
<p>Wrong icons (diferent then mockup)</p><p><br></p><p>In mockup:</p><p><img src="blob:https://friendly-plans.testquality.com/7bb52068-0ade-4e7e-a970-1a2e36debf59" style="width: 300px;" class="fr-fic fr-dib"></p><p><br></p><p>In app:</p><p><img src="blob:https://friendly-plans.testquality.com/46bf1f39-5130-4105-a974-0f1c79141c43" style="width: 300px;" class="fr-fic fr-dib"></p>

**Comment by DorotaBabinska** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D2. Do not remove or edit.` [D2](https://friendly-plans.testquality.com/project/6444/result/1131324/defect/4008)

**Comment by DorotaBabinska** [comment]
More details and sreenshots in TestQuality.

**Comment by mikolevy** [comment]
Has been done in #116
