### ISSUE TITLE
[BUG] Display settings for child - bad layout for text elements [D3]

### ISSUE THREAD

**Issue by DorotaBabinska** [autyzm-pg/friendly-plans-react#46]
<p>In mockup icons of &#39;tekst&#39; i &#39;rozmiar tekstu&#39; are in the same line:</p><p><img src="blob:https://friendly-plans.testquality.com/27d65bb1-9d72-4034-9fc3-3036ae3a1016" style="width: 300px;" class="fr-fic fr-dib"></p><p>In app:</p><p><img src="blob:https://friendly-plans.testquality.com/cbebe426-5cce-4a99-a56d-3cbbc9125bbc" style="width: 300px;" class="fr-fic fr-dib"></p>

**Comment by DorotaBabinska** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D3. Do not remove or edit.` [D3](https://friendly-plans.testquality.com/project/6444/result/1131324/defect/4010)

**Comment by DorotaBabinska** [comment]
More details and sreenshots in TestQuality.

**Comment by mikolevy** [comment]
Has been done in #116
