### ISSUE TITLE
[BUG] Display settings for child - different swich [D4]

### ISSUE THREAD

**Issue by DorotaBabinska** [autyzm-pg/friendly-plans-react#47]
<p>Switch of &#39;Przewijanie kart w widoku slajdu&#39; is different than in mockup.</p><p><br></p><p>In mockup:</p><p><img src="blob:https://friendly-plans.testquality.com/9707b93b-836e-4701-a212-b889f2d59f44" style="width: 300px;" class="fr-fic fr-dib"></p><p><br></p><p>In app:</p><p><img src="blob:https://friendly-plans.testquality.com/3e48940e-3653-4df5-b539-22a3158c9923" style="width: 300px;" class="fr-fic fr-dib"></p>

**Comment by DorotaBabinska** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D4. Do not remove or edit.` [D4](https://friendly-plans.testquality.com/project/6444/result/1131324/defect/4011)

**Comment by DorotaBabinska** [comment]
More details and sreenshots in TestQuality.

**Comment by mikolevy** [comment]
Has been done in #116
