### ISSUE TITLE
Settings - show proper init value for 'handle scroll card in slide mode' setting ([BUG] Save child settings [D5])

### ISSUE THREAD

**Issue by DorotaBabinska** [autyzm-pg/friendly-plans-react#48]
<p>&#39;Przewijanie kart w widoku slajdu&#39; is not saved.</p>

**Comment by DorotaBabinska** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D5. Do not remove or edit.` [D5](https://friendly-plans.testquality.com/project/6444/result/1131325/defect/4012)

**Comment by DorotaBabinska** [comment]
More details and sreenshots in TestQuality.

**Comment by DorotaBabinska** [comment]
More details and sreenshots in TestQuality.

**Comment by mikolevy** [comment]
It looks like it's saving in the db however init value is displayed wrong - currently, it's always "true" on init.

AC: When open settings view 'handle scroll card in slide mode' setting shows value reflecting Student settings
