### ISSUE TITLE
[BUG] Tasks - create simple task - save not working [D6]

### ISSUE THREAD

**Issue by DorotaBabinska** [autyzm-pg/friendly-plans-react#49]
<p>App allowes to enter task data but does not save the task.</p><p><br></p><p><strong>Steps:</strong></p><p>1. Choose child&#39;s plan to edit</p><p><img src="blob:https://friendly-plans.testquality.com/647ab155-114c-4fb2-b226-a4a4124fc0a0" style="width: 300px;" class="fr-fic fr-dib"></p><p>2. Click &#39;Add task&#39;</p><p><img src="blob:https://friendly-plans.testquality.com/02a9ef36-3321-44c9-b68b-954f176fb85f" style="width: 300px;" class="fr-fic fr-dib"></p><p>3. Add task data</p><p><img src="blob:https://friendly-plans.testquality.com/7da1b0cc-8518-4e43-af10-dfacf48e6352" style="width: 300px;" class="fr-fic fr-dib"></p><p>4. Back to plan</p><p><img src="blob:https://friendly-plans.testquality.com/c5760b80-092b-41dc-8ac0-55e36081d74e" style="width: 300px;" class="fr-fic fr-dib"></p><p>5. Task is not saved</p><p><img src="blob:https://friendly-plans.testquality.com/120b93f0-eee7-4198-a6f7-4141a7084f73" style="width: 300px;" class="fr-fic fr-dib"></p>

**Comment by DorotaBabinska** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D6. Do not remove or edit.` [D6](https://friendly-plans.testquality.com/project/6444/result/1131313/defect/4013)

**Comment by DorotaBabinska** [comment]
More details and sreenshots in TestQuality.

**Comment by mikolevy** [comment]
Solved by #59 

TBD: update in TestQuality (credentials needed ;) )
