### ISSUE TITLE
[BUG] Create simple task - add picture [D8]

### ISSUE THREAD

**Issue by DorotaBabinska** [autyzm-pg/friendly-plans-react#51]
<p>Missing 2 options of choosing picture sorce.</p><p><br></p><p>In mockup:</p><p><img src="blob:https://friendly-plans.testquality.com/2c318d8d-31e1-47ee-b907-6e47f4dda2e4" style="width: 300px;" class="fr-fic fr-dib"></p><p><br></p><p>In app:</p><p><img src="blob:https://friendly-plans.testquality.com/2c4b777a-23b3-43c9-b776-a15454a962da" style="width: 300px;" class="fr-fic fr-dib"></p>

Missing options are:
- add from library
- record short movie

We should decide would it be in the scope of MVP. If so, I think we should create separated tasks for implementing each of those.

**Comment by DorotaBabinska** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D8. Do not remove or edit.` [D8](https://friendly-plans.testquality.com/project/6444/result/1131315/defect/4015)

**Comment by DorotaBabinska** [comment]
More details and screenshots in TestQuality.

**Comment by mikolevy** [comment]
To implement this I think we should decide about handling images (#78)

**Comment by PrzemekPopowicz** [comment]
Closing as covered by #23
