### ISSUE TITLE
Q: Plans tasks - changing tasks order and already done tasks

### ISSUE THREAD

**Issue by mikolevy** [autyzm-pg/friendly-plans-react#77]
How should we handle changing tasks order in the context of already done tasks?

Ask Teacher for undoing all tasks? Block action with info?

**Comment by PrzemekPopowicz** [comment]
Always start from beginning -> run and show not done tasks.

If all tasks are done or 0 tasks - disable play

If child finishes plan then clear all done tasks

Add button to enable/disable all tasks (ux)
