### ISSUE TITLE
Student settings button only on the dashboard

### ISSUE THREAD

**Issue by mikolevy** [autyzm-pg/friendly-plans-react#95]
We should show settings button only on the dashboard as in the mockup:

AC:
- The settings button and select student button are hidden on Plan View, Task View 

![image](https://user-images.githubusercontent.com/9513577/67469016-d2bb9680-f64b-11e9-8bc1-2d9210dd1017.png)

> On new designs we don't have possibility to change Settings/Student from Edit Plan View (which makes sense for me :) ) so that problem won't exists anymore. Just to confirm - should hide that settings button on Edit Plan View?
> 
> In #92 magasol wrote: 
> 
> I noticed a problem with run plan from edit view, update plan doesn't subscribe to student so display setting doesn't update automatically but I didn't change that yet because of refactoring
> 
> Idea: Add new component for running plan in both modes (over slide and list mode), subscribe for Student in this component and pass as prop to particular run plan screen.
> 
> AC: Student settings (eg. font size) is respected when we run plan from any place (from dashboard, from edit plan view) and in any mode (list/slide)

**Comment by PrzemekPopowicz** [comment]
How is it going? Do you need any help with that?

**Comment by Cervera96** [comment]
![image](https://user-images.githubusercontent.com/41299075/75965299-d5de5300-5e85-11ea-9bd6-0b28b06b2540.png)

![image](https://user-images.githubusercontent.com/41299075/75965385-00c8a700-5e86-11ea-91c6-bc05b38ee651.png)


The settings button is appearing just in the Dashboard screen

**Comment by pwysowski** [comment]
It looks like it was done before ;)
